// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {db} from '../models';
import {app} from '../models';

export function AddDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddDownloadPreset(arg1:config.DownloadPreset):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function ClearCompletedDownloads():Promise<void>;

export function DeleteVideo(arg1:string):Promise<void>;

export function GetAppName():Promise<string>;

export function GetChannels():Promise<Array<string>>;

export function GetDownloadPresets():Promise<Array<config.DownloadPreset>>;

export function GetDownloads():Promise<Array<db.Download>>;

export function GetDownloadsByStatus(arg1:string):Promise<Array<db.Download>>;

export function GetLibraryStats():Promise<Record<string, any>>;

export function GetSettings():Promise<config.Config>;

export function GetVersion():Promise<string>;

export function GetVideo(arg1:string):Promise<app.VideoResult>;

export function GetVideoByYoutubeID(arg1:string):Promise<app.VideoResult>;

export function GetVideoInfo(arg1:string):Promise<app.VideoInfoResult>;

export function ListVideos(arg1:app.ListVideosOptions):Promise<Array<app.VideoResult>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function RemoveDownloadPreset(arg1:string):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function RetryDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function ShowError(arg1:string):Promise<void>;

export function ShowOpenDirectoryDialog():Promise<string>;

export function ShowSaveDialog(arg1:string):Promise<string>;

export function UpdateDownloadPreset(arg1:string,arg2:config.DownloadPreset):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function UpdateWatchPosition(arg1:string,arg2:number):Promise<void>;

export function ValidateURL(arg1:string):Promise<boolean>;
