// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {app} from '../models';
import {db} from '../models';

export function AddDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddDownloadPreset(arg1:config.DownloadPreset):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CancelEditJob(arg1:string):Promise<void>;

export function CheckDownloadStatus(arg1:string):Promise<Record<string, any>>;

export function CheckFFmpegWithGuidance():Promise<app.FFmpegCheckResult>;

export function CleanUpDuplicateVideos():Promise<void>;

export function CleanupOrphanedFiles(arg1:boolean):Promise<Record<string, any>>;

export function ClearCompletedDownloads():Promise<void>;

export function ClearCompletedDownloadsCache():Promise<void>;

export function ClearDownloadCache():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearTempFiles():Promise<Record<string, any>>;

export function DeleteEditJob(arg1:string):Promise<void>;

export function DeleteVideo(arg1:string,arg2:boolean):Promise<void>;

export function DeleteVideoWithConfirmation(arg1:string):Promise<Record<string, any>>;

export function ExportLogs(arg1:string):Promise<void>;

export function GetAllLogs():Promise<Array<app.LogEntry>>;

export function GetAppName():Promise<string>;

export function GetCacheInfo():Promise<app.CacheInfo>;

export function GetChannels():Promise<Array<string>>;

export function GetCropPresets():Promise<Record<string, Record<string, any>>>;

export function GetDownloadPresets():Promise<Array<config.DownloadPreset>>;

export function GetDownloadQueue():Promise<Array<app.DownloadResult>>;

export function GetDownloads():Promise<Array<db.Download>>;

export function GetDownloadsByStatus(arg1:string):Promise<Array<db.Download>>;

export function GetEditJobStatus(arg1:string):Promise<app.EditJobResult>;

export function GetEditPresets():Promise<Array<app.EditPresetResult>>;

export function GetEffectRanges():Promise<Record<string, Record<string, any>>>;

export function GetFFmpegInstallGuide():Promise<app.InstallGuide>;

export function GetIncompleteDownloads():Promise<Array<db.Download>>;

export function GetLibraryStats():Promise<Record<string, any>>;

export function GetLogExportPath():Promise<string>;

export function GetLogs(arg1:number):Promise<Array<app.LogEntry>>;

export function GetPreviewImage(arg1:string):Promise<string>;

export function GetRotationOptions():Promise<Array<Record<string, any>>>;

export function GetSettings():Promise<config.Config>;

export function GetSupportedCodecs():Promise<Record<string, Record<string, any>>>;

export function GetSupportedFormats():Promise<Record<string, Record<string, any>>>;

export function GetVersion():Promise<string>;

export function GetVideo(arg1:string):Promise<app.VideoResult>;

export function GetVideoByYoutubeID(arg1:string):Promise<app.VideoResult>;

export function GetVideoFile(arg1:string):Promise<Array<number>>;

export function GetVideoInfo(arg1:string):Promise<app.VideoInfoResult>;

export function GetVideoMetadata(arg1:string):Promise<app.VideoMetadataResult>;

export function GetWatermarkPositions():Promise<Record<string, string>>;

export function GetYtdlpVersion():Promise<string>;

export function ListEditJobs(arg1:string):Promise<Array<app.EditJobResult>>;

export function ListVideos(arg1:app.ListVideosOptions):Promise<Array<app.VideoResult>>;

export function OpenFFmpegDownloadPage():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function PreviewEdit(arg1:string,arg2:string,arg3:app.EditSettingsInput):Promise<string>;

export function RemoveDownloadPreset(arg1:string):Promise<void>;

export function RepairLibrary():Promise<Record<string, any>>;

export function RestoreDownloadQueue():Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function RetryDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SetLogExportPath(arg1:string):Promise<void>;

export function ShowError(arg1:string):Promise<void>;

export function ShowFFmpegDialog():Promise<string>;

export function ShowOpenDirectoryDialog():Promise<string>;

export function ShowSaveDialog(arg1:string):Promise<string>;

export function StartProcessingDownloads():Promise<void>;

export function SubmitEditJob(arg1:string,arg2:string,arg3:app.EditSettingsInput):Promise<string>;

export function SyncDownloadWithFile(arg1:string):Promise<void>;

export function UpdateDownloadPreset(arg1:string,arg2:config.DownloadPreset):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function UpdateWatchPosition(arg1:string,arg2:number):Promise<void>;

export function UpdateYtdlp():Promise<boolean>;

export function ValidateURL(arg1:string):Promise<boolean>;

export function VerifyAndRepairDownloads():Promise<void>;
