// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddDownload'](arg1, arg2, arg3);
}

export function AddDownloadPreset(arg1) {
  return window['go']['app']['App']['AddDownloadPreset'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function ClearCompletedDownloads() {
  return window['go']['app']['App']['ClearCompletedDownloads']();
}

export function DeleteVideo(arg1) {
  return window['go']['app']['App']['DeleteVideo'](arg1);
}

export function GetAppName() {
  return window['go']['app']['App']['GetAppName']();
}

export function GetChannels() {
  return window['go']['app']['App']['GetChannels']();
}

export function GetDownloadPresets() {
  return window['go']['app']['App']['GetDownloadPresets']();
}

export function GetDownloads() {
  return window['go']['app']['App']['GetDownloads']();
}

export function GetDownloadsByStatus(arg1) {
  return window['go']['app']['App']['GetDownloadsByStatus'](arg1);
}

export function GetLibraryStats() {
  return window['go']['app']['App']['GetLibraryStats']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function GetVideo(arg1) {
  return window['go']['app']['App']['GetVideo'](arg1);
}

export function GetVideoByYoutubeID(arg1) {
  return window['go']['app']['App']['GetVideoByYoutubeID'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['app']['App']['GetVideoInfo'](arg1);
}

export function ListVideos(arg1) {
  return window['go']['app']['App']['ListVideos'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['app']['App']['PauseDownload'](arg1);
}

export function RemoveDownloadPreset(arg1) {
  return window['go']['app']['App']['RemoveDownloadPreset'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['app']['App']['ResumeDownload'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['app']['App']['RetryDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function ShowError(arg1) {
  return window['go']['app']['App']['ShowError'](arg1);
}

export function ShowOpenDirectoryDialog() {
  return window['go']['app']['App']['ShowOpenDirectoryDialog']();
}

export function ShowSaveDialog(arg1) {
  return window['go']['app']['App']['ShowSaveDialog'](arg1);
}

export function UpdateDownloadPreset(arg1, arg2) {
  return window['go']['app']['App']['UpdateDownloadPreset'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['app']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateWatchPosition(arg1, arg2) {
  return window['go']['app']['App']['UpdateWatchPosition'](arg1, arg2);
}

export function ValidateURL(arg1) {
  return window['go']['app']['App']['ValidateURL'](arg1);
}
