// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddDownload'](arg1, arg2, arg3);
}

export function AddDownloadPreset(arg1) {
  return window['go']['app']['App']['AddDownloadPreset'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function CheckDownloadStatus(arg1) {
  return window['go']['app']['App']['CheckDownloadStatus'](arg1);
}

export function CleanUpDuplicateVideos() {
  return window['go']['app']['App']['CleanUpDuplicateVideos']();
}

export function CleanupOrphanedFiles(arg1) {
  return window['go']['app']['App']['CleanupOrphanedFiles'](arg1);
}

export function ClearCompletedDownloads() {
  return window['go']['app']['App']['ClearCompletedDownloads']();
}

export function ClearCompletedDownloadsCache() {
  return window['go']['app']['App']['ClearCompletedDownloadsCache']();
}

export function ClearDownloadCache() {
  return window['go']['app']['App']['ClearDownloadCache']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function ClearTempFiles() {
  return window['go']['app']['App']['ClearTempFiles']();
}

export function DeleteVideo(arg1, arg2) {
  return window['go']['app']['App']['DeleteVideo'](arg1, arg2);
}

export function DeleteVideoWithConfirmation(arg1) {
  return window['go']['app']['App']['DeleteVideoWithConfirmation'](arg1);
}

export function ExportLogs(arg1) {
  return window['go']['app']['App']['ExportLogs'](arg1);
}

export function GetAllLogs() {
  return window['go']['app']['App']['GetAllLogs']();
}

export function GetAppName() {
  return window['go']['app']['App']['GetAppName']();
}

export function GetCacheInfo() {
  return window['go']['app']['App']['GetCacheInfo']();
}

export function GetChannels() {
  return window['go']['app']['App']['GetChannels']();
}

export function GetDownloadPresets() {
  return window['go']['app']['App']['GetDownloadPresets']();
}

export function GetDownloadQueue() {
  return window['go']['app']['App']['GetDownloadQueue']();
}

export function GetDownloads() {
  return window['go']['app']['App']['GetDownloads']();
}

export function GetDownloadsByStatus(arg1) {
  return window['go']['app']['App']['GetDownloadsByStatus'](arg1);
}

export function GetIncompleteDownloads() {
  return window['go']['app']['App']['GetIncompleteDownloads']();
}

export function GetLibraryStats() {
  return window['go']['app']['App']['GetLibraryStats']();
}

export function GetLogExportPath() {
  return window['go']['app']['App']['GetLogExportPath']();
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function GetVideo(arg1) {
  return window['go']['app']['App']['GetVideo'](arg1);
}

export function GetVideoByYoutubeID(arg1) {
  return window['go']['app']['App']['GetVideoByYoutubeID'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['app']['App']['GetVideoInfo'](arg1);
}

export function GetYtdlpVersion() {
  return window['go']['app']['App']['GetYtdlpVersion']();
}

export function ListVideos(arg1) {
  return window['go']['app']['App']['ListVideos'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['app']['App']['PauseDownload'](arg1);
}

export function RemoveDownloadPreset(arg1) {
  return window['go']['app']['App']['RemoveDownloadPreset'](arg1);
}

export function RepairLibrary() {
  return window['go']['app']['App']['RepairLibrary']();
}

export function RestoreDownloadQueue() {
  return window['go']['app']['App']['RestoreDownloadQueue']();
}

export function ResumeDownload(arg1) {
  return window['go']['app']['App']['ResumeDownload'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['app']['App']['RetryDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SetLogExportPath(arg1) {
  return window['go']['app']['App']['SetLogExportPath'](arg1);
}

export function ShowError(arg1) {
  return window['go']['app']['App']['ShowError'](arg1);
}

export function ShowFFmpegDialog() {
  return window['go']['app']['App']['ShowFFmpegDialog']();
}

export function ShowOpenDirectoryDialog() {
  return window['go']['app']['App']['ShowOpenDirectoryDialog']();
}

export function ShowSaveDialog(arg1) {
  return window['go']['app']['App']['ShowSaveDialog'](arg1);
}

export function StartProcessingDownloads() {
  return window['go']['app']['App']['StartProcessingDownloads']();
}

export function SyncDownloadWithFile(arg1) {
  return window['go']['app']['App']['SyncDownloadWithFile'](arg1);
}

export function UpdateDownloadPreset(arg1, arg2) {
  return window['go']['app']['App']['UpdateDownloadPreset'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['app']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateWatchPosition(arg1, arg2) {
  return window['go']['app']['App']['UpdateWatchPosition'](arg1, arg2);
}

export function UpdateYtdlp() {
  return window['go']['app']['App']['UpdateYtdlp']();
}

export function ValidateURL(arg1) {
  return window['go']['app']['App']['ValidateURL'](arg1);
}

export function VerifyAndRepairDownloads() {
  return window['go']['app']['App']['VerifyAndRepairDownloads']();
}
